// Shape of the entity snapshots generated by scripts/build-entities.mjs:
//   data.json  — full per-entity stats (heavy; imported by entity page routes)
//   index.json — slugs / names / gating only (light; imported broadly)

export type EntityCardRef = {
  id: string;
  name: string;
  number: string;
  rarity?: string;
  marketPrice?: number;
  imageSmall?: string;
  imageLarge?: string;
};

export type EntitySetRef = { id: string; name: string; releaseDate: string };

export type PokemonEntity = {
  dex: number;
  slug: string;
  name: string;
  cardCount: number;
  /** Special Illustration Rares. */
  sirCount: number;
  /** Illustration Rare + Special Illustration Rare. */
  illustrationRareCount: number;
  artistCount: number;
  setCount: number;
  firstSet: EntitySetRef;
  latestSet: EntitySetRef;
  rarities: Record<string, number>;
  signatureCard?: EntityCardRef;
};

export type ArtistTopSpecies = { slug: string; name: string; count: number };

export type ArtistEntity = {
  slug: string;
  name: string;
  cardCount: number;
  setCount: number;
  illustrationCount: number;
  earliestSet: EntitySetRef;
  latestSet: EntitySetRef;
  topPokemon: ArtistTopSpecies[];
  signatureCard?: EntityCardRef;
};

export type ArtistIndexEntry = { slug: string; name: string; cardCount: number; setCount: number };

export type EntitySnapshot = {
  asOf: string;
  thresholds: { artistMinCards: number };
  pokemon: PokemonEntity[];
  artists: ArtistEntity[];
  artistIndex: ArtistIndexEntry[];
};

export type PokemonCatalogEntry = { dex: number; slug: string; name: string; cardCount: number };

export type EntityCatalog = {
  asOf: string;
  thresholds: { artistMinCards: number };
  pokemon: PokemonCatalogEntry[];
  artists: ArtistIndexEntry[];
};
